# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
require "yaml"
settings = YAML.load_file "settings.yaml"


Vagrant.configure(2) do |config|
	config.vm.box = settings["software"]["box"]
	config.vm.boot_timeout = settings["software"]["boot_timeout"] 
	
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "jenkins"
		node1_config.vm.network "private_network", ip: settings["nodes"]["ip1"]
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", settings["nodes"]["memory"]]
			vb.customize ["modifyvm", :id, "--cpus", settings["nodes"]["cpu"]]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
		node1_config.vm.provision "shell", path: "scripts/jenkins.sh"
	end  
end
