# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.boot_timeout = 300 
	
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "jenkins"
		node1_config.vm.network "private_network", ip:"172.17.8.163"
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "2024"]
			vb.customize ["modifyvm", :id, "--cpus", "2"]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
		node1_config.vm.provision "shell", path: "scripts/jenkins.sh"
	end  
end
