# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.define :jenkins do |jenkins_config|
		jenkins_config.vm.host_name = "jenkins"
		jenkins_config.vm.network "private_network", ip:"172.17.8.163"
  end
  

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = "2048"
  end
  
  config.vm.provision "shell" do |shell|
    shell.path = "scripts/jenkins.sh"
	
  end

  
end
