# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"
	config.vbguest.installer_options = { allow_kernel_upgrade: true }
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "node1"
		node1_config.vm.network "private_network", ip:"172.17.11.4"
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "2024"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
		end
		node1_config.vm.provision "shell", path: "scripts/common-controller.sh"
		node1_config.vm.provision "shell", path: "scripts/ansible.sh"
	end
	
	config.vm.define :node2 do |node2_config|
		node2_config.vm.host_name = "node2"
		node2_config.vm.network "private_network", ip:"172.17.11.5"
		node2_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "2072"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
		end
		node2_config.vm.provision "shell", path: "scripts/common-target.sh"
	end
	
end