# -*- mode: ruby -*-
# vi: set ft=ruby :
require "yaml"
settings = YAML.load_file "settings.yaml"

Vagrant.configure(2) do |config|
	config.vm.box = settings["software"]["box"]
	config.vm.boot_timeout = settings["software"]["boot_timeout"]
	
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "node1"
		node1_config.vm.boot_timeout = 600
		node1_config.vm.network "private_network", ip:settings["node1"]["ip"]
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", settings["node1"]["memory"]]
			vb.customize ["modifyvm", :id, "--cpus", settings["node1"]["cpu"]]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
		node1_config.vm.provision "shell", path: "scripts/tools.sh"
	end
	
	#config.vm.define :node2 do |node2_config|
		#node2_config.vm.host_name = "node2"
		#node2_config.vm.network "private_network", ip:settings["node2"]["ip"]
		#node2_config.vm.provider :virtualbox do |vb|
			#vb.customize ["modifyvm", :id, "--memory", settings["node2"]["memory"]]
			#vb.customize ["modifyvm", :id, "--cpus", settings["node2"]["cpu"]]
			#vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		#end
		#node2_config.vm.provision "shell", path: "scripts/tools.sh"
	#end
	
end