# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
require "yaml"
settings = YAML.load_file "settings.yaml"


Vagrant.configure("2") do |config|
  config.vm.box = settings["software"]["box"]
  

  config.vm.define :tomcat do |tomcat_config|
		tomcat_config.vm.host_name = "tomcat"
		tomcat_config.vm.network "private_network", ip:settings["nodes"]["ip1"]
		
	end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = settings["nodes"]["cpu"]
    vb.memory = settings["nodes"]["memory"]
  end
  
  config.vm.provision "shell" do |shell|
    shell.path = "scripts/tomcat.sh"
  end

end
