# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "bento/ubuntu-20.04"
	
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "node01"
		node1_config.vm.network "private_network", ip:"10.10.1.120"
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "2024"]
			vb.customize ["modifyvm", :id, "--cpus", "2"]
		end
	end
	config.vm.define :node2 do |node2_config|
		node2_config.vm.host_name = "node02"
		node2_config.vm.network "private_network", ip:"10.10.1.122"
		node2_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "1024"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
		end
	end
	
end

