# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"
	
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "chefworkstation"
		node1_config.vm.network "private_network", ip:"172.25.36.4"
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "1500"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end
	
	config.vm.define :node2 do |node2_config|
		node2_config.vm.host_name = "chefserver"
		node2_config.vm.network "private_network", ip:"172.25.36.5"
		node2_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "2048"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end
	config.vm.define :node3 do |node3_config|
		node3_config.vm.host_name = "chefnode"
		node3_config.vm.network "private_network", ip:"172.25.36.6"
		node3_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "1500"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end
	
end