# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"
	
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "elk-machine"
		node1_config.vm.network "private_network", ip:"192.168.12.11"
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "4096"]
			vb.customize ["modifyvm", :id, "--cpus", "2"]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end
	end
	config.vm.provision "shell" do |shell|
	shell.path = "scripts/elk.sh"
	
	end
	
	
	
end