# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "bento/ubuntu-20.04"
	config.vm.boot_timeout= 1440
	
	config.vm.define :node2 do |node2_config|
		node2_config.vm.host_name = "node2"
		node2_config.vm.network "private_network", ip:"172.17.8.105"
		node2_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "1672"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
		end
		node2_config.vm.provision "shell", path: "scripts/node_exporter.sh"
	end
	config.vm.define :node1 do |node1_config|
		node1_config.vm.host_name = "node1"
		node1_config.vm.network "private_network", ip:"172.17.8.104"
		node1_config.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--memory", "2024"]
			vb.customize ["modifyvm", :id, "--cpus", "1"]
		end
		node1_config.vm.provision "shell", path: "scripts/node_exporter.sh"
		node1_config.vm.provision "shell", path: "scripts/prometheus.sh"
		node1_config.vm.provision "shell", path: "scripts/grafana.sh"
		
	end
	
	
	
end